//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  services_es: Services_Es;
  services_esConnection: Services_EsConnection;
  services_ru: Services_Ru;
  services_ruConnection: Services_RuConnection;
  services_en: Services_En;
  services_enConnection: Services_EnConnection;
  team_es: Team_Es;
  team_esConnection: Team_EsConnection;
  team_ru: Team_Ru;
  team_ruConnection: Team_RuConnection;
  team_en: Team_En;
  team_enConnection: Team_EnConnection;
  pages: Pages;
  pagesConnection: PagesConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryServices_EsArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryServices_EsConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<Services_EsFilter>;
};


export type QueryServices_RuArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryServices_RuConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<Services_RuFilter>;
};


export type QueryServices_EnArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryServices_EnConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<Services_EnFilter>;
};


export type QueryTeam_EsArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryTeam_EsConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<Team_EsFilter>;
};


export type QueryTeam_RuArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryTeam_RuConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<Team_RuFilter>;
};


export type QueryTeam_EnArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryTeam_EnConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<Team_EnFilter>;
};


export type QueryPagesArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryPagesConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PagesFilter>;
};

export type DocumentFilter = {
  services_es?: InputMaybe<Services_EsFilter>;
  services_ru?: InputMaybe<Services_RuFilter>;
  services_en?: InputMaybe<Services_EnFilter>;
  team_es?: InputMaybe<Team_EsFilter>;
  team_ru?: InputMaybe<Team_RuFilter>;
  team_en?: InputMaybe<Team_EnFilter>;
  pages?: InputMaybe<PagesFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = Services_Es | Services_Ru | Services_En | Team_Es | Team_Ru | Team_En | Pages | Folder;

export type Services_Es = Node & Document & {
  __typename?: 'Services_es';
  title: Scalars['String']['output'];
  price?: Maybe<Scalars['String']['output']>;
  image?: Maybe<Scalars['String']['output']>;
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type ImageFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type RichTextFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Services_EsFilter = {
  title?: InputMaybe<StringFilter>;
  price?: InputMaybe<StringFilter>;
  image?: InputMaybe<ImageFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type Services_EsConnectionEdges = {
  __typename?: 'Services_esConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Services_Es>;
};

export type Services_EsConnection = Connection & {
  __typename?: 'Services_esConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<Services_EsConnectionEdges>>>;
};

export type Services_Ru = Node & Document & {
  __typename?: 'Services_ru';
  title: Scalars['String']['output'];
  price?: Maybe<Scalars['String']['output']>;
  image?: Maybe<Scalars['String']['output']>;
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type Services_RuFilter = {
  title?: InputMaybe<StringFilter>;
  price?: InputMaybe<StringFilter>;
  image?: InputMaybe<ImageFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type Services_RuConnectionEdges = {
  __typename?: 'Services_ruConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Services_Ru>;
};

export type Services_RuConnection = Connection & {
  __typename?: 'Services_ruConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<Services_RuConnectionEdges>>>;
};

export type Services_En = Node & Document & {
  __typename?: 'Services_en';
  title: Scalars['String']['output'];
  price?: Maybe<Scalars['String']['output']>;
  image?: Maybe<Scalars['String']['output']>;
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type Services_EnFilter = {
  title?: InputMaybe<StringFilter>;
  price?: InputMaybe<StringFilter>;
  image?: InputMaybe<ImageFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type Services_EnConnectionEdges = {
  __typename?: 'Services_enConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Services_En>;
};

export type Services_EnConnection = Connection & {
  __typename?: 'Services_enConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<Services_EnConnectionEdges>>>;
};

export type Team_Es = Node & Document & {
  __typename?: 'Team_es';
  name: Scalars['String']['output'];
  position?: Maybe<Scalars['String']['output']>;
  photo?: Maybe<Scalars['String']['output']>;
  bio?: Maybe<Scalars['String']['output']>;
  email?: Maybe<Scalars['String']['output']>;
  phone?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type Team_EsFilter = {
  name?: InputMaybe<StringFilter>;
  position?: InputMaybe<StringFilter>;
  photo?: InputMaybe<ImageFilter>;
  bio?: InputMaybe<StringFilter>;
  email?: InputMaybe<StringFilter>;
  phone?: InputMaybe<StringFilter>;
};

export type Team_EsConnectionEdges = {
  __typename?: 'Team_esConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Team_Es>;
};

export type Team_EsConnection = Connection & {
  __typename?: 'Team_esConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<Team_EsConnectionEdges>>>;
};

export type Team_Ru = Node & Document & {
  __typename?: 'Team_ru';
  name: Scalars['String']['output'];
  position?: Maybe<Scalars['String']['output']>;
  photo?: Maybe<Scalars['String']['output']>;
  bio?: Maybe<Scalars['String']['output']>;
  email?: Maybe<Scalars['String']['output']>;
  phone?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type Team_RuFilter = {
  name?: InputMaybe<StringFilter>;
  position?: InputMaybe<StringFilter>;
  photo?: InputMaybe<ImageFilter>;
  bio?: InputMaybe<StringFilter>;
  email?: InputMaybe<StringFilter>;
  phone?: InputMaybe<StringFilter>;
};

export type Team_RuConnectionEdges = {
  __typename?: 'Team_ruConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Team_Ru>;
};

export type Team_RuConnection = Connection & {
  __typename?: 'Team_ruConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<Team_RuConnectionEdges>>>;
};

export type Team_En = Node & Document & {
  __typename?: 'Team_en';
  name: Scalars['String']['output'];
  position?: Maybe<Scalars['String']['output']>;
  photo?: Maybe<Scalars['String']['output']>;
  bio?: Maybe<Scalars['String']['output']>;
  email?: Maybe<Scalars['String']['output']>;
  phone?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type Team_EnFilter = {
  name?: InputMaybe<StringFilter>;
  position?: InputMaybe<StringFilter>;
  photo?: InputMaybe<ImageFilter>;
  bio?: InputMaybe<StringFilter>;
  email?: InputMaybe<StringFilter>;
  phone?: InputMaybe<StringFilter>;
};

export type Team_EnConnectionEdges = {
  __typename?: 'Team_enConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Team_En>;
};

export type Team_EnConnection = Connection & {
  __typename?: 'Team_enConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<Team_EnConnectionEdges>>>;
};

export type Pages = Node & Document & {
  __typename?: 'Pages';
  title: Scalars['String']['output'];
  language: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type PagesFilter = {
  title?: InputMaybe<StringFilter>;
  language?: InputMaybe<StringFilter>;
  slug?: InputMaybe<StringFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type PagesConnectionEdges = {
  __typename?: 'PagesConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Pages>;
};

export type PagesConnection = Connection & {
  __typename?: 'PagesConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<PagesConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updateServices_es: Services_Es;
  createServices_es: Services_Es;
  updateServices_ru: Services_Ru;
  createServices_ru: Services_Ru;
  updateServices_en: Services_En;
  createServices_en: Services_En;
  updateTeam_es: Team_Es;
  createTeam_es: Team_Es;
  updateTeam_ru: Team_Ru;
  createTeam_ru: Team_Ru;
  updateTeam_en: Team_En;
  createTeam_en: Team_En;
  updatePages: Pages;
  createPages: Pages;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdateServices_EsArgs = {
  relativePath: Scalars['String']['input'];
  params: Services_EsMutation;
};


export type MutationCreateServices_EsArgs = {
  relativePath: Scalars['String']['input'];
  params: Services_EsMutation;
};


export type MutationUpdateServices_RuArgs = {
  relativePath: Scalars['String']['input'];
  params: Services_RuMutation;
};


export type MutationCreateServices_RuArgs = {
  relativePath: Scalars['String']['input'];
  params: Services_RuMutation;
};


export type MutationUpdateServices_EnArgs = {
  relativePath: Scalars['String']['input'];
  params: Services_EnMutation;
};


export type MutationCreateServices_EnArgs = {
  relativePath: Scalars['String']['input'];
  params: Services_EnMutation;
};


export type MutationUpdateTeam_EsArgs = {
  relativePath: Scalars['String']['input'];
  params: Team_EsMutation;
};


export type MutationCreateTeam_EsArgs = {
  relativePath: Scalars['String']['input'];
  params: Team_EsMutation;
};


export type MutationUpdateTeam_RuArgs = {
  relativePath: Scalars['String']['input'];
  params: Team_RuMutation;
};


export type MutationCreateTeam_RuArgs = {
  relativePath: Scalars['String']['input'];
  params: Team_RuMutation;
};


export type MutationUpdateTeam_EnArgs = {
  relativePath: Scalars['String']['input'];
  params: Team_EnMutation;
};


export type MutationCreateTeam_EnArgs = {
  relativePath: Scalars['String']['input'];
  params: Team_EnMutation;
};


export type MutationUpdatePagesArgs = {
  relativePath: Scalars['String']['input'];
  params: PagesMutation;
};


export type MutationCreatePagesArgs = {
  relativePath: Scalars['String']['input'];
  params: PagesMutation;
};

export type DocumentUpdateMutation = {
  services_es?: InputMaybe<Services_EsMutation>;
  services_ru?: InputMaybe<Services_RuMutation>;
  services_en?: InputMaybe<Services_EnMutation>;
  team_es?: InputMaybe<Team_EsMutation>;
  team_ru?: InputMaybe<Team_RuMutation>;
  team_en?: InputMaybe<Team_EnMutation>;
  pages?: InputMaybe<PagesMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  services_es?: InputMaybe<Services_EsMutation>;
  services_ru?: InputMaybe<Services_RuMutation>;
  services_en?: InputMaybe<Services_EnMutation>;
  team_es?: InputMaybe<Team_EsMutation>;
  team_ru?: InputMaybe<Team_RuMutation>;
  team_en?: InputMaybe<Team_EnMutation>;
  pages?: InputMaybe<PagesMutation>;
};

export type Services_EsMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  price?: InputMaybe<Scalars['String']['input']>;
  image?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type Services_RuMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  price?: InputMaybe<Scalars['String']['input']>;
  image?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type Services_EnMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  price?: InputMaybe<Scalars['String']['input']>;
  image?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type Team_EsMutation = {
  name?: InputMaybe<Scalars['String']['input']>;
  position?: InputMaybe<Scalars['String']['input']>;
  photo?: InputMaybe<Scalars['String']['input']>;
  bio?: InputMaybe<Scalars['String']['input']>;
  email?: InputMaybe<Scalars['String']['input']>;
  phone?: InputMaybe<Scalars['String']['input']>;
};

export type Team_RuMutation = {
  name?: InputMaybe<Scalars['String']['input']>;
  position?: InputMaybe<Scalars['String']['input']>;
  photo?: InputMaybe<Scalars['String']['input']>;
  bio?: InputMaybe<Scalars['String']['input']>;
  email?: InputMaybe<Scalars['String']['input']>;
  phone?: InputMaybe<Scalars['String']['input']>;
};

export type Team_EnMutation = {
  name?: InputMaybe<Scalars['String']['input']>;
  position?: InputMaybe<Scalars['String']['input']>;
  photo?: InputMaybe<Scalars['String']['input']>;
  bio?: InputMaybe<Scalars['String']['input']>;
  email?: InputMaybe<Scalars['String']['input']>;
  phone?: InputMaybe<Scalars['String']['input']>;
};

export type PagesMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  language?: InputMaybe<Scalars['String']['input']>;
  slug?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type Services_EsPartsFragment = { __typename: 'Services_es', title: string, price?: string | null, image?: string | null, body?: any | null };

export type Services_RuPartsFragment = { __typename: 'Services_ru', title: string, price?: string | null, image?: string | null, body?: any | null };

export type Services_EnPartsFragment = { __typename: 'Services_en', title: string, price?: string | null, image?: string | null, body?: any | null };

export type Team_EsPartsFragment = { __typename: 'Team_es', name: string, position?: string | null, photo?: string | null, bio?: string | null, email?: string | null, phone?: string | null };

export type Team_RuPartsFragment = { __typename: 'Team_ru', name: string, position?: string | null, photo?: string | null, bio?: string | null, email?: string | null, phone?: string | null };

export type Team_EnPartsFragment = { __typename: 'Team_en', name: string, position?: string | null, photo?: string | null, bio?: string | null, email?: string | null, phone?: string | null };

export type PagesPartsFragment = { __typename: 'Pages', title: string, language: string, slug: string, body?: any | null };

export type Services_EsQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type Services_EsQuery = { __typename?: 'Query', services_es: { __typename: 'Services_es', id: string, title: string, price?: string | null, image?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type Services_EsConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<Services_EsFilter>;
}>;


export type Services_EsConnectionQuery = { __typename?: 'Query', services_esConnection: { __typename?: 'Services_esConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'Services_esConnectionEdges', cursor: string, node?: { __typename: 'Services_es', id: string, title: string, price?: string | null, image?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type Services_RuQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type Services_RuQuery = { __typename?: 'Query', services_ru: { __typename: 'Services_ru', id: string, title: string, price?: string | null, image?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type Services_RuConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<Services_RuFilter>;
}>;


export type Services_RuConnectionQuery = { __typename?: 'Query', services_ruConnection: { __typename?: 'Services_ruConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'Services_ruConnectionEdges', cursor: string, node?: { __typename: 'Services_ru', id: string, title: string, price?: string | null, image?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type Services_EnQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type Services_EnQuery = { __typename?: 'Query', services_en: { __typename: 'Services_en', id: string, title: string, price?: string | null, image?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type Services_EnConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<Services_EnFilter>;
}>;


export type Services_EnConnectionQuery = { __typename?: 'Query', services_enConnection: { __typename?: 'Services_enConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'Services_enConnectionEdges', cursor: string, node?: { __typename: 'Services_en', id: string, title: string, price?: string | null, image?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type Team_EsQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type Team_EsQuery = { __typename?: 'Query', team_es: { __typename: 'Team_es', id: string, name: string, position?: string | null, photo?: string | null, bio?: string | null, email?: string | null, phone?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type Team_EsConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<Team_EsFilter>;
}>;


export type Team_EsConnectionQuery = { __typename?: 'Query', team_esConnection: { __typename?: 'Team_esConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'Team_esConnectionEdges', cursor: string, node?: { __typename: 'Team_es', id: string, name: string, position?: string | null, photo?: string | null, bio?: string | null, email?: string | null, phone?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type Team_RuQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type Team_RuQuery = { __typename?: 'Query', team_ru: { __typename: 'Team_ru', id: string, name: string, position?: string | null, photo?: string | null, bio?: string | null, email?: string | null, phone?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type Team_RuConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<Team_RuFilter>;
}>;


export type Team_RuConnectionQuery = { __typename?: 'Query', team_ruConnection: { __typename?: 'Team_ruConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'Team_ruConnectionEdges', cursor: string, node?: { __typename: 'Team_ru', id: string, name: string, position?: string | null, photo?: string | null, bio?: string | null, email?: string | null, phone?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type Team_EnQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type Team_EnQuery = { __typename?: 'Query', team_en: { __typename: 'Team_en', id: string, name: string, position?: string | null, photo?: string | null, bio?: string | null, email?: string | null, phone?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type Team_EnConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<Team_EnFilter>;
}>;


export type Team_EnConnectionQuery = { __typename?: 'Query', team_enConnection: { __typename?: 'Team_enConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'Team_enConnectionEdges', cursor: string, node?: { __typename: 'Team_en', id: string, name: string, position?: string | null, photo?: string | null, bio?: string | null, email?: string | null, phone?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type PagesQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type PagesQuery = { __typename?: 'Query', pages: { __typename: 'Pages', id: string, title: string, language: string, slug: string, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type PagesConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PagesFilter>;
}>;


export type PagesConnectionQuery = { __typename?: 'Query', pagesConnection: { __typename?: 'PagesConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'PagesConnectionEdges', cursor: string, node?: { __typename: 'Pages', id: string, title: string, language: string, slug: string, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export const Services_EsPartsFragmentDoc = gql`
    fragment Services_esParts on Services_es {
  __typename
  title
  price
  image
  body
}
    `;
export const Services_RuPartsFragmentDoc = gql`
    fragment Services_ruParts on Services_ru {
  __typename
  title
  price
  image
  body
}
    `;
export const Services_EnPartsFragmentDoc = gql`
    fragment Services_enParts on Services_en {
  __typename
  title
  price
  image
  body
}
    `;
export const Team_EsPartsFragmentDoc = gql`
    fragment Team_esParts on Team_es {
  __typename
  name
  position
  photo
  bio
  email
  phone
}
    `;
export const Team_RuPartsFragmentDoc = gql`
    fragment Team_ruParts on Team_ru {
  __typename
  name
  position
  photo
  bio
  email
  phone
}
    `;
export const Team_EnPartsFragmentDoc = gql`
    fragment Team_enParts on Team_en {
  __typename
  name
  position
  photo
  bio
  email
  phone
}
    `;
export const PagesPartsFragmentDoc = gql`
    fragment PagesParts on Pages {
  __typename
  title
  language
  slug
  body
}
    `;
export const Services_EsDocument = gql`
    query services_es($relativePath: String!) {
  services_es(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...Services_esParts
  }
}
    ${Services_EsPartsFragmentDoc}`;
export const Services_EsConnectionDocument = gql`
    query services_esConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: Services_esFilter) {
  services_esConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...Services_esParts
      }
    }
  }
}
    ${Services_EsPartsFragmentDoc}`;
export const Services_RuDocument = gql`
    query services_ru($relativePath: String!) {
  services_ru(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...Services_ruParts
  }
}
    ${Services_RuPartsFragmentDoc}`;
export const Services_RuConnectionDocument = gql`
    query services_ruConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: Services_ruFilter) {
  services_ruConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...Services_ruParts
      }
    }
  }
}
    ${Services_RuPartsFragmentDoc}`;
export const Services_EnDocument = gql`
    query services_en($relativePath: String!) {
  services_en(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...Services_enParts
  }
}
    ${Services_EnPartsFragmentDoc}`;
export const Services_EnConnectionDocument = gql`
    query services_enConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: Services_enFilter) {
  services_enConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...Services_enParts
      }
    }
  }
}
    ${Services_EnPartsFragmentDoc}`;
export const Team_EsDocument = gql`
    query team_es($relativePath: String!) {
  team_es(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...Team_esParts
  }
}
    ${Team_EsPartsFragmentDoc}`;
export const Team_EsConnectionDocument = gql`
    query team_esConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: Team_esFilter) {
  team_esConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...Team_esParts
      }
    }
  }
}
    ${Team_EsPartsFragmentDoc}`;
export const Team_RuDocument = gql`
    query team_ru($relativePath: String!) {
  team_ru(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...Team_ruParts
  }
}
    ${Team_RuPartsFragmentDoc}`;
export const Team_RuConnectionDocument = gql`
    query team_ruConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: Team_ruFilter) {
  team_ruConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...Team_ruParts
      }
    }
  }
}
    ${Team_RuPartsFragmentDoc}`;
export const Team_EnDocument = gql`
    query team_en($relativePath: String!) {
  team_en(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...Team_enParts
  }
}
    ${Team_EnPartsFragmentDoc}`;
export const Team_EnConnectionDocument = gql`
    query team_enConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: Team_enFilter) {
  team_enConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...Team_enParts
      }
    }
  }
}
    ${Team_EnPartsFragmentDoc}`;
export const PagesDocument = gql`
    query pages($relativePath: String!) {
  pages(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...PagesParts
  }
}
    ${PagesPartsFragmentDoc}`;
export const PagesConnectionDocument = gql`
    query pagesConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: PagesFilter) {
  pagesConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...PagesParts
      }
    }
  }
}
    ${PagesPartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      services_es(variables: Services_EsQueryVariables, options?: C): Promise<{data: Services_EsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: Services_EsQueryVariables, query: string}> {
        return requester<{data: Services_EsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: Services_EsQueryVariables, query: string}, Services_EsQueryVariables>(Services_EsDocument, variables, options);
      },
    services_esConnection(variables?: Services_EsConnectionQueryVariables, options?: C): Promise<{data: Services_EsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: Services_EsConnectionQueryVariables, query: string}> {
        return requester<{data: Services_EsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: Services_EsConnectionQueryVariables, query: string}, Services_EsConnectionQueryVariables>(Services_EsConnectionDocument, variables, options);
      },
    services_ru(variables: Services_RuQueryVariables, options?: C): Promise<{data: Services_RuQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: Services_RuQueryVariables, query: string}> {
        return requester<{data: Services_RuQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: Services_RuQueryVariables, query: string}, Services_RuQueryVariables>(Services_RuDocument, variables, options);
      },
    services_ruConnection(variables?: Services_RuConnectionQueryVariables, options?: C): Promise<{data: Services_RuConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: Services_RuConnectionQueryVariables, query: string}> {
        return requester<{data: Services_RuConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: Services_RuConnectionQueryVariables, query: string}, Services_RuConnectionQueryVariables>(Services_RuConnectionDocument, variables, options);
      },
    services_en(variables: Services_EnQueryVariables, options?: C): Promise<{data: Services_EnQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: Services_EnQueryVariables, query: string}> {
        return requester<{data: Services_EnQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: Services_EnQueryVariables, query: string}, Services_EnQueryVariables>(Services_EnDocument, variables, options);
      },
    services_enConnection(variables?: Services_EnConnectionQueryVariables, options?: C): Promise<{data: Services_EnConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: Services_EnConnectionQueryVariables, query: string}> {
        return requester<{data: Services_EnConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: Services_EnConnectionQueryVariables, query: string}, Services_EnConnectionQueryVariables>(Services_EnConnectionDocument, variables, options);
      },
    team_es(variables: Team_EsQueryVariables, options?: C): Promise<{data: Team_EsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: Team_EsQueryVariables, query: string}> {
        return requester<{data: Team_EsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: Team_EsQueryVariables, query: string}, Team_EsQueryVariables>(Team_EsDocument, variables, options);
      },
    team_esConnection(variables?: Team_EsConnectionQueryVariables, options?: C): Promise<{data: Team_EsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: Team_EsConnectionQueryVariables, query: string}> {
        return requester<{data: Team_EsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: Team_EsConnectionQueryVariables, query: string}, Team_EsConnectionQueryVariables>(Team_EsConnectionDocument, variables, options);
      },
    team_ru(variables: Team_RuQueryVariables, options?: C): Promise<{data: Team_RuQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: Team_RuQueryVariables, query: string}> {
        return requester<{data: Team_RuQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: Team_RuQueryVariables, query: string}, Team_RuQueryVariables>(Team_RuDocument, variables, options);
      },
    team_ruConnection(variables?: Team_RuConnectionQueryVariables, options?: C): Promise<{data: Team_RuConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: Team_RuConnectionQueryVariables, query: string}> {
        return requester<{data: Team_RuConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: Team_RuConnectionQueryVariables, query: string}, Team_RuConnectionQueryVariables>(Team_RuConnectionDocument, variables, options);
      },
    team_en(variables: Team_EnQueryVariables, options?: C): Promise<{data: Team_EnQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: Team_EnQueryVariables, query: string}> {
        return requester<{data: Team_EnQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: Team_EnQueryVariables, query: string}, Team_EnQueryVariables>(Team_EnDocument, variables, options);
      },
    team_enConnection(variables?: Team_EnConnectionQueryVariables, options?: C): Promise<{data: Team_EnConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: Team_EnConnectionQueryVariables, query: string}> {
        return requester<{data: Team_EnConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: Team_EnConnectionQueryVariables, query: string}, Team_EnConnectionQueryVariables>(Team_EnConnectionDocument, variables, options);
      },
    pages(variables: PagesQueryVariables, options?: C): Promise<{data: PagesQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PagesQueryVariables, query: string}> {
        return requester<{data: PagesQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PagesQueryVariables, query: string}, PagesQueryVariables>(PagesDocument, variables, options);
      },
    pagesConnection(variables?: PagesConnectionQueryVariables, options?: C): Promise<{data: PagesConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PagesConnectionQueryVariables, query: string}> {
        return requester<{data: PagesConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PagesConnectionQueryVariables, query: string}, PagesConnectionQueryVariables>(PagesConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "http://localhost:4001/graphql",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

  